CONTACTS = [
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-09-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Default valid contact [1]",
    ),
    (
        {
            "firstName": "Bob",
            "lastName": "Ross",
            "birthdate": "1942-10-29",
            "email": "bob.ross@mail.com",
            "phone": "1234567890",
            "street1": "Kingston Ave, 706",
            "city": "Daytona Beach",
            "stateProvince": "FL",
            "postalCode": "22222",
            "country": "USA",
        },
        "Default valid contact [2]",
    ),
    (
        {
            "firstName": "Bob",
            "lastName": "Dylan",
        },
        "Minimum data",
    ),
    (
        {
            "firstName": "Leap",
            "lastName": "Year",
            "birthdate": "2000-02-29",
            "email": "leap.year@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Leap year date with 29th February",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "+551234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Phone with country code with plus [1]",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "+1222333444",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Phone with country code with plus [2]",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "+48222333444",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Phone with country code with plus [3]",
    ),
    (
        {
            "firstName": "Bob",
            "lastName": "Ross",
            "birthdate": "1942-10-29",
            "email": "bob.ross@mail.com",
            "phone": "+1234567890",
            "street1": "Kingston Ave, 706",
            "city": "Daytona Beach",
            "stateProvince": "FL",
            "postalCode": "22222",
            "country": "USA",
        },
        "Phone with country code with plus [4]",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "111222333",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Phone with 9 digits without contry code",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "street1 with max allowed len 40",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "street2 with max allowed len 40",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "city with max allowed len 40",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "aaaaaaaaaabbbbbbbbbb",
            "postalCode": "10118",
            "country": "USA",
        },
        "stateProvince with max allowed len 20",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "111",
            "country": "USA",
        },
        "postalCode with min allowed len 3",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "1111111",
            "country": "USA",
        },
        "postalCode with max allowed len 7",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd",
        },
        "country with max allowed len 40",
    ),
]

CONTACTS_INVALID = [
    (
        {
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Field firstName is missing",
    ),
    (
        {
            "firstName": "Will",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Field lastName is missing",
    ),
    (
        {
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Both firstName and lastName fields are missing",
    ),
    (
        {

        },
        "Empty body",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Empty birthdate",
    ),
    (
        {
            "firstName": "Future",
            "lastName": "Guy",
            "birthdate": "3034-03-10",
            "email": "future.guy@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Birthdate in the future",
    ),
    (
        {
            "firstName": "No Leap",
            "lastName": "Year",
            "birthdate": "2001-02-29",
            "email": "noleap.year@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Non leap year birthdate with 29th February",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "2024-08-32",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Birthdate with 32th day",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "2024-09-31",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Birthdate with 31th day but only 30 exist",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-13-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Birthdate with 13th month",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-00-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Birthdate with 00th month",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1899-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Birthdate with year less than 1900",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-09-25",
            "email": "",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Empty email",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smithmail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Email without @",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Email without user",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Email without domain",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Email with space",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Email with invalid domain",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "w!ll.s#&?^@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Email with invalid characters",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-09-25",
            "email": "will.smith@mail.com",
            "phone": "",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Empty phone",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "12a4567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "Phone with letters",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddde",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "street1 right above max len with 41 characters",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddde",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "street2 right above max len with 41 characters",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddde",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "USA",
        },
        "city right above max len with 41 characters",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "aaaaaaaaaabbbbbbbbbbc",
            "postalCode": "10118",
            "country": "USA",
        },
        "stateProvince right above max len with 21 characters",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "11",
            "country": "USA",
        },
        "postalCode right below min len with 2 digits",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "11111111",
            "country": "USA",
        },
        "postalCode right above max len with 8 digits",
    ),
    (
        {
            "firstName": "Will",
            "lastName": "Smith",
            "birthdate": "1968-10-25",
            "email": "will.smith@mail.com",
            "phone": "1234567890",
            "street1": "1 Main St.",
            "street2": "Apartment A",
            "city": "New York",
            "stateProvince": "NY",
            "postalCode": "10118",
            "country": "aaaaaaaaaabbbbbbbbbbccccccccccdddddddddde",
        },
        "country right above max len with 41 characters",
    ),
]
